/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author proxc
 */
public class Contract extends javax.swing.JFrame {

    /**
     * Creates new form Home_Data
     */
    public Contract() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        Bien = new javax.swing.JTextField();
        Entrer = new javax.swing.JToggleButton();
        Client = new javax.swing.JTextField();
        ID = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        Suprimer = new javax.swing.JToggleButton();
        Type = new javax.swing.JComboBox<>();
        Enregistrer = new javax.swing.JToggleButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(5, 57, 44));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel15.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(214, 184, 132));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/images/Design_sans_titre_2.png"))); // NOI18N
        jLabel15.setText("Contract");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 46, 300, 76));

        Bien.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        Bien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BienActionPerformed(evt);
            }
        });
        jPanel1.add(Bien, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 50, 100, -1));

        Entrer.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        Entrer.setText("Entrer");
        Entrer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EntrerActionPerformed(evt);
            }
        });
        jPanel1.add(Entrer, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 100, 100, -1));

        Client.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        Client.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClientActionPerformed(evt);
            }
        });
        jPanel1.add(Client, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 50, 100, -1));

        ID.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        ID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IDActionPerformed(evt);
            }
        });
        jPanel1.add(ID, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 50, 100, -1));

        jLabel3.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(214, 184, 132));
        jLabel3.setText("ID");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 30, -1, -1));

        jLabel6.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(214, 184, 132));
        jLabel6.setText("Bien");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 30, -1, -1));

        jLabel8.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(214, 184, 132));
        jLabel8.setText("Client");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 30, -1, -1));

        jLabel9.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(214, 184, 132));
        jLabel9.setText("Type");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 30, -1, -1));

        Suprimer.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        Suprimer.setText("Suprimer");
        Suprimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SuprimerActionPerformed(evt);
            }
        });
        jPanel1.add(Suprimer, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 100, 100, -1));

        Type.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Vente", "Location", " " }));
        jPanel1.add(Type, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 50, 120, -1));

        Enregistrer.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        Enregistrer.setText("enregistrer");
        Enregistrer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EnregistrerActionPerformed(evt);
            }
        });
        jPanel1.add(Enregistrer, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 100, 110, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1070, 150));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Bien", "Client", "Type"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable1);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 1070, 520));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void EntrerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EntrerActionPerformed
        DefaultTableModel model = ( DefaultTableModel )jTable1.getModel();
        
        String Nomclient = Bien.getText();
        String IDimmo = ID.getText();
        String Prenomclient = Client.getText();
        Object etatImmo = Type.getSelectedItem();
        int selectedRowIndex = jTable1.getSelectedRow();
        model.addRow(new Object[]{ID.getText(), Bien.getText(),Client.getText(),Type.getSelectedItem()});
        
    }//GEN-LAST:event_EntrerActionPerformed

    private void BienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BienActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BienActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
        int selectedRowIndex = jTable1.getSelectedRow();
        ID.setText(model.getValueAt(selectedRowIndex, 0).toString());
        Bien.setText(model.getValueAt(selectedRowIndex, 1).toString());
        Client.setText(model.getValueAt(selectedRowIndex, 2).toString());
        Type.setName(model.getValueAt(selectedRowIndex, 3).toString());
    }//GEN-LAST:event_jTable1MouseClicked

    private void IDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IDActionPerformed

    private void ClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClientActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ClientActionPerformed

    private void SuprimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SuprimerActionPerformed
                DefaultTableModel model = ( DefaultTableModel )jTable1.getModel();
        

        try{
        int SelectedRowIndex = jTable1.getSelectedRow();
        model.removeRow(SelectedRowIndex);
        }catch(Exception ex){
            JOptionPane.showMessageDialog(null, ex);
            
        }
    }//GEN-LAST:event_SuprimerActionPerformed

    private void EnregistrerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EnregistrerActionPerformed
        DefaultTableModel model = ( DefaultTableModel )jTable1.getModel();
        if(model.getRowCount()==0){
            JOptionPane.showMessageDialog(this, "table vide");
        }else{
            String Nomclient,IDimmo,Prenomclient,etatImmo;
            try{
                Class.forName("com.mysql.jdbc.driver");
                Connection con = DriverManager.getConnection("jdbc:oracle:thin//localhost:1521/xe");
                for(int i=0;i<model.getRowCount();i++){
                    Nomclient = model.getValueAt(i, 0).toString();
                    IDimmo = model.getValueAt(i, 1).toString();
                    Prenomclient = model.getValueAt(i, 2).toString();
                    etatImmo = model.getValueAt(i, 3).toString();
                    
                    String query ="insert into subject(id,superficie,ville, etat,prix)values(?,?,?)";
                    PreparedStatement prepstmt = con.prepareStatement(query);
                    prepstmt.setString(1,Nomclient);
                    prepstmt.setString(2,IDimmo);
                    prepstmt.setString(3,Prenomclient);
                    prepstmt.setString(4,etatImmo);
                    
                    prepstmt.execute();
                    JOptionPane.showMessageDialog(this, "table enregistrer");
                            
                    
                    
                }
            }catch(Exception e){
                
            }
        }
    }//GEN-LAST:event_EnregistrerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home_Data.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home_Data.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home_Data.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home_Data.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Contract().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Bien;
    private javax.swing.JTextField Client;
    private javax.swing.JToggleButton Enregistrer;
    private javax.swing.JToggleButton Entrer;
    private javax.swing.JTextField ID;
    private javax.swing.JToggleButton Suprimer;
    private javax.swing.JComboBox<String> Type;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
